---
title: "A Model for Spectrogram Surfaces"
author: "J.P. Meagher"
date: "24 October 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I have already performed a Principal Components Analysis on the vectorised spectrogram surfaces, however in doing this I overlooked some of the underlying assumptions of PCA and did not define my model for the Spectrograms. In trying to write down a full model for the spectrogram surfaces, from which the features and feature weights which will inform the ancestral reconstruction are drawn from, I hope to go some way to resolving these problems. 

# Spectrogram Surfaces and the Bat Phylogeny

## The Data

The data provided for this analysis consists of 1816 echolocation call recordings for 449 bats from 22 species. Call recordings are not uniformly spread over bats or bat species. These call recordings are preprocessed such that each is represented by a smooth spectrogram surface mapped to an absolute time scale. The smoothed spectrogram is represented by a uniform $50 \times 104$ grid over the $T \times F$ space where $F \in [9, 212] kHz$ and $T \in [0, 1]$.

Accompanying these call recordings is an estimated Bat Phylogeny $P$ describing our best guess at the evolutionary relationships between species of bat.

## Surfaces as Gaussian Processes

In order to provide a framework within which an ancestral reconstruction analysis can be performed we assume that each spectrogram surface is a realisation of a Phylogenetic Gaussian Process such that a smoothed spectrogram surface can be denoted $\mathbf{Y}^n_{i,j}(t, \omega, \mathbf{p})$. This is the surface representing the $j^{th}$ call from the $i^{th}$ bat from the species observed at point $\mathbf{p}$ on $\mathbf{P}$, and so the surface is a function of time $t$, frequency $\omega$, and $\mathbf{p}$. Thus we claim that 

$$
\mathbf{Y}_{i,j}(t, \omega, \mathbf{p}) \sim \mathcal{N}(\mu(t, \omega, \mathbf{p}), \Sigma(t, t', \omega, \omega', \mathbf{p}, \mathbf{p}'))
$$

In order to allow this analysis to proceed the simplifying assumption that the covariance is separable over the surface space and the phylogenetic space. This implies that $\Sigma(\omega, \omega', t, t', \mathbf{p}, \mathbf{p}') = \Sigma_{\mathbf{S}}(\omega, \omega', t, t') \Sigma_{\mathbf{P}}(\mathbf{p}, \mathbf{p}')$, where $\mathbf{S} = T \times F$. Thus, when considering the surface at point $\mathbf{p}$, the phylogenetic portion of the covariance becomes $\Sigma_{\mathbf{P}}(\mathbf{p}, \mathbf{p}) = 1$ by definition. This leads to the simplified expression **I think this is given by Jones and Moriarty in the PGPR paper but I am winging this section a bit**

$$
\mathbf{Y}^{\mathbf{p}}_{i,j}(t, \omega) \sim \mathcal{N}(\mu^{\mathbf{p}}(t, \omega), \Sigma_{\mathbf{S}}(\omega, \omega', t, t'))
$$

As the covariance is separable, for any surface
Suppose that this surface was generated by a Gaussian process such that $\mathbf{Y}^n_{i,j}(t, \omega) \sim \mathcal{N}(\mu_i^n(\omega, t), \Sigma_i^n(\omega, \omega', t, t'))$, where $\mu_i^n$ is the mean surface function for the specific bat and $\Sigma_i^n$ is the covariance operator. Thus the surface under consideration can be written as

$$
\mathbf{Y}^n_{i,j} = \mu^n_i + \epsilon^n_{i,j}
$$

where $\epsilon^n_{i,j} \sim \mathcal{N} (\mathbf{0}, \Sigma_i^n(\omega, \omega', t, t'))$.

Now consider the individual level mean function, $\mu_i^n(\omega, t)$. This mean function also depends on the position of bat species $n$ on the bat phylogenetic tree $\mathbf{P}$, representing the position of the bat species in evolutionary space. Denote the position of species $n$ on $\mathbf{P}$ by $\mathbf{p}$. With this in mind suppose that $\mu_i^n(\omega, t, \mathbf{p}) \sim \mathcal{N}(\mu^n(\omega, t, \mathbf{p}), \Sigma^n(\omega, \omega', t, t', \mathbf{p}, \mathbf{p}'))$

Now consider the mean surface for the $i^{th}$ bat in species $n$. Suppose that the $n^{th}$ species has a characteristic mean surface and that each individual bats calls are subject to a zero mean noise process. We then write

$$
\mu^n_i = \mu^n + \mathbf{\epsilon}^n_{i}
$$

The final layer of this model concerns the global mean spectrogram surface for echolocation calls to which a zero mean noise process can be added to generate the spectrogram surface for species $n$. This implies

$$
\mu^n = \mu + \mathbf{\gamma}^n
$$
And so the original surface can be considered to be subject to 3 levels of noise process, species, bat and recording levels. This can then be written as

$$
\mathbf{Y}^n_{i,j} = \mu + \gamma^n + \epsilon^n_{i} + \upsilon^n_{i,j}
$$

It is the species level of noise, $\gamma^n$ that I am interested in modelling. This looks very like a mixed effects model.
